const reasons = {
  REJECT_FLAGGED_AS_SPAM: 'REJECT_FLAGGED_AS_SPAM',
  REJECT_TOO_MANY_SADFACES: 'REJECT_TOO_MANY_SADFACES',
  REJECT_BY_REVIEWER: 'REJECT_BY_REVIEWER',
  PASS_BY_REVIEWER: 'PASS_BY_REVIEWER'
}

module.exports = { reasons }